---
version: '3.7'

services:
  frontend:
    container_name: flask
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8080:5000
    volumes:
      - mediafiles:/media
volumes:
  mediafiles:
    name: mediafiles
